# Generated by Django 2.2.14 on 2022-07-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, default=(2022, 7, 10)),
            preserve_default=False,
        ),
    ]
