# Generated by Django 2.2.14 on 2022-07-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0002_tip_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
