# Generated by Django 2.2.14 on 2022-07-11 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0004_auto_20220711_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='fecha_creacion',
            field=models.DateTimeField(verbose_name=datetime.datetime.now),
        ),
    ]
