# Generated by Django 2.2.14 on 2022-07-11 19:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0006_auto_20220711_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='fecha_creacion',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
