# Generated by Django 2.2.14 on 2022-07-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0007_auto_20220711_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
