# Generated by Django 2.2.14 on 2022-07-11 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0009_auto_20220711_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='fecha_creacion',
            field=models.DateField(verbose_name=datetime.datetime.now),
        ),
    ]
